#!/usr/bin/env bash

# rofi power menu
chosen=$(echo -e " Lock\n鈴 Suspend\n漏 Reboot\n襤 Shutdown" | rofi -p power -dmenu -i -lines 4)
if [[ $chosen == *"Lock"* ]]; then
  betterlockscreen --lock dimblur
elif [[ $chosen == *"Suspend"* ]]; then
  # lock && sleep 1
  systemctl suspend
elif [[ $chosen == *"Reboot"* ]]; then
  # lock && sleep 1
  systemctl reboot
elif [[ $chosen == *"Shutdown"* ]]; then
  # lock && sleep 1
  systemctl poweroff
fi
