#! /bin/sh

# app settings
export DE_TERM="alacritty"
export DE_LAUNCH="rofi -show drun"
export DE_BROWSE="google-chrome"

# kill
killall sxhkd
killall picom
killall dunst
killall feh

# autostart
# xss-lock -l -- betterlockscreen --lock dimblur &
sxhkd &
picom --experimental-backends &
dunst &
feh --recursive --randomize --bg-fill "$HOME/Pictures/wallpapers/" &
# xsetroot -cursor_name left_ptr &

# monitor
bspc monitor -d I II III IV V VI VII VIII IX X

# window config
bspc config border_width         3
bspc config window_gap           5

# layout config
bspc config automatic_scheme     alternate
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# mouse config
bspc config focus_by_distance       true
bspc config focus_follows_pointer   true
bspc config click_to_focus          true
bspc config pointer_follows_monitor true

bspc config pointer_modifier        mod1
bspc config pointer_action1         resize_side
bspc config pointer_action1         resize_corner
bspc config pointer_action3         move

# color config
bspc config normal_border_color  "#484848"
bspc config focused_border_color "#1F8999"
bspc config urgent_border_color  "#B58900"
bspc config presel_border_color  "#26E2FF"

bspc rule -a '*:nemo'     state=floating center=true
bspc rule -a Lxappearance state=floating

bspc rule -a Gimp         desktop='^8' state=floating follow=on
bspc rule -a Chromium     desktop='^2'
bspc rule -a mplayer2     state=floating
bspc rule -a Kupfer.py    focus=on
bspc rule -a Screenkey    manage=off
